"""init

Revision ID: e51bddd7a406
Revises: 5f205abd1333
Create Date: 2025-10-25 20:55:33.055084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e51bddd7a406'
down_revision = '5f205abd1333'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('season', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_series_number', ['series_id', 'number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('season', schema=None) as batch_op:
        batch_op.drop_constraint('uq_series_number', type_='unique')

    # ### end Alembic commands ###
